# Generated by Django 2.2.3 on 2020-01-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='body',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
